# Generated by Django 5.0.4 on 2024-05-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_rename_name_pet_petname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
